# Generated by Django 5.0.6 on 2024-05-29 12:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=250)),
                ('phase_done_percentage', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_curator', models.CharField(max_length=250)),
                ('project_name', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('project_done_percentage', models.CharField(max_length=20)),
                ('project_start_date', models.DateTimeField(auto_now=True)),
                ('project_deadline', models.DateTimeField()),
                ('project_budget', models.CharField(max_length=30)),
                ('project_spent_money', models.CharField(max_length=30)),
                ('project_documents', models.FileField(upload_to='files/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_steps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyihalar.phase')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='files')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyihalar.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=250)),
                ('task_done_percentage', models.CharField(default=0, max_length=20)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyihalar.phase')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='step_tasks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyihalar.task'),
        ),
    ]
