# Generated by Django 5.0.6 on 2024-06-03 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_steps',
        ),
        migrations.RemoveField(
            model_name='project',
            name='step_tasks',
        ),
        migrations.AddField(
            model_name='phase',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='loyihalar.project'),
            preserve_default=False,
        ),
    ]
