# Generated by Django 5.0.6 on 2024-06-03 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0002_remove_project_project_steps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_documents',
        ),
    ]
