# Generated by Django 5.0.6 on 2024-06-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0003_remove_project_project_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='phase_description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
