# Generated by Django 5.0.6 on 2024-06-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0004_phase_phase_description_alter_documents_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='phase_description',
        ),
    ]
