# Generated by Django 5.0.6 on 2024-06-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0006_project_project_status_task_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='type',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('Yangi', 'Yangi'), ('Jarayonda', 'Jarayonda'), ('Tugatilgan', 'Tugatilgan')], default='Yangi', max_length=30),
        ),
    ]
