# Generated by Django 5.0.6 on 2024-06-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0007_documents_type_documents_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
