# Generated by Django 5.0.6 on 2024-05-29 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hodimlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
