# Generated by Django 5.0.6 on 2024-06-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hodimlar', '0005_alter_user_blog_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='human.jpg', max_length=300, upload_to='images/'),
        ),
    ]
